version: '3.7'
services:

  server:
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=src/app
      - ORDER_MANAGEMENT_HOST=localhost
      - ORDER_MANAGEMENT_PORT=5000
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=trips
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USERNAME=
      - DATABASE_PASSWD=
      - DATABASE_PATH=db/server.db
      - DATABASE_DIALECT=sqlite
      - DATABASE_DRIVER=
    image: courier
    container_name: courier-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fixtures:/app/fixtures
      - ./src:/app/src
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
   
networks:
  default:
    name: courier-net
    external: true