version: '3.7'
services:

  server:
    container_name: courier-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports: 
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports: 
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181