version: '3.7'
services:

  server:
    image: courier
    container_name: courier-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fixtures:/app/fixtures
      - ./src:/app/src
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
   
networks:
  default:
    name: courier-net
    external: true