version: '3.7'
services:
  server:
    container_name: python_devserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
